//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyHelpMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestedInRegistered
    {
        public int InterestedInRegisteredNum { get; set; }
        public string ID { get; set; }
        public int TaskDateNum { get; set; }
        public Nullable<System.DateTime> SignToTaskTime { get; set; }
    
        public virtual TaskInDates TaskInDates { get; set; }
        public virtual Users Users { get; set; }
    }
}
